<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.erika.springshop</groupId>
    <artifactId>springshop-ecommerce</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>_SpringShop E-Commerce</name>
    <description>Monorepo for SpringShop E-Commerce microservices</description>

    <modules>
        <!-- Shared Modules -->
        <module>common/commons-core</module>
        <module>common/commons-security</module>

        <!-- Microservices -->
        <module>services/gateway-service</module>
        <module>services/inventory-service</module>
        <module>services/notification-service</module>
        <module>services/order-service</module>
        <module>services/payment-service</module>
        <module>services/product-service</module>
        <module>services/user-service</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <spring.boot.version>3.4.5</spring.boot.version>
        <maven.compiler.plugin.version>3.14.0</maven.compiler.plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <!-- Compiler -->
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.plugin.version}</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                    </configuration>
                </plugin>

                <!-- Spring Boot -->
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
