spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springshop
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # ou validate, create-drop conforme ambiente
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  profiles:
    active: default